version: '3'

services:
  frontend:
    image: ${REGISTRY}/${IMAGE_NAME}:latest
    container_name: react-frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Mount SSL certificates if using HTTPS
      - ./certs:/etc/nginx/certs:ro
      # Mount custom nginx configuration if needed
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      # Add any other environment variables your app needs

# Define a custom network
networks:
  app-network:
    driver: bridge 